This if the codebook for the file d.tidy that was generated by run_analysis.R for the Getting and Cleaning the Data Corsera Project.

Variables:

1. Subject - subject ID, 30 unique subjects
2. Activity - Activity, possible values are: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING,LAYING
3. Remaining variables: 79 variables of means and standard deviations.
The variable names are constructed using the following abbreviations:
Part 1:
  time = time
  freq = frequency
Part 2:
  body = body 
  gravity = gravity
Part 3:
  gyro = gyroscope
  acc = accelerometer
Part 4:
  jerk = jerk
Part 5:
  mag = magnitude
Part 6:
  mean = mean
  std = standard deviation

Note: not all parts are included in each variable name
